### ISSUE TITLE
Create database diagrams for main tables

### ISSUE THREAD

**Issue by vovsike** [Prisposoba/prisposoba#7]
We need some sort of diagrams for our database.

Logical or even conceptual ones will do.

**Comment by Iv-Alex** [comment]
We have to use MVC model

this must be taken into account when planning

**Comment by vovsike** [comment]
![Prisposoba](https://user-images.githubusercontent.com/57632637/110970562-c7a4fb80-8351-11eb-9770-2700a8ce640c.png)

This is our first diagram that we will improve in the future
