### ISSUE TITLE
Rent out hosting for hosting our database and deploy database

### ISSUE THREAD

**Issue by vovsike** [Prisposoba/prisposoba#8]
We need a centralised hosting to host our database. As well as renting and installing database we need to write up documentation of how database was deployed. 

Another thing that we need to do is to create a database folder in this repo where we will store tools to manipulate the database.

**Comment by Iv-Alex** [comment]
What are you think about https://www.heroku.com/

**Comment by vovsike** [comment]
I had a look, looks good to me. We need to look at limitations for free use.

**Comment by vovsike** [comment]
We now have a hosting and database is deployed documentation will be written in a separate issue. Our hosting is jino.ru

**Comment by vovsike** [comment]
Documentation issue #10
